#!/bin/bash
# Need to have Circuit Python mpy cross compiler in base project directory,
# executable and named mpy-cross.
# Download from: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/mpy-cross/

# continue script even if error occurs
set +e

# make mpy files
for FILE in src_qtpy/lib/*.py; do ./mpy-cross-7.3.3 $FILE; done; 

# copy the default calibrate file if it does not exist on the board
if ! [ -f /media/alan/CIRCUITPY/calibrate.py ]; then
    cp calibrate_default.py /media/alan/CIRCUITPY/calibrate.py
fi

# found that it was more reliable to delete the code.py file first before
# copying a new one.
if [ -f /media/alan/CIRCUITPY/code.py ]; then
    rm /media/alan/CIRCUITPY/code.py
fi
sleep 1

# copy the code.py file last so that all other files are in place before starting the
# main script (code.py)
cp src_qtpy/lib/*.mpy /media/alan/CIRCUITPY/lib/
cp src_qtpy/code.py /media/alan/CIRCUITPY/code.py
