[project]
name = "lora-power-monitor"
version = "0.1.0"
description = "LoRaWAN Electric Power Monitor"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minimalmodbus>=2.1.1",
    "pyinstaller>=6.12.0",
    "pyserial>=3.5",
    "questionary>=2.1.0",
]
